[project]
name = "vietnam-lottery-xsmb-analysis"
version = "0.1.0"
description = "Using GitHub Action to automatically fetch and analyze results of the Vietnam lottery daily."
authors = [
    {name = "Khiem Doan", email = "doankhiem.crazy@gmail.com"},
]

readme = "README.md"
license = {text = "MIT"}

requires-python = ">=3.12"

dependencies = [
    "tzdata",
    "pydantic>=2.12",
    "pydantic-settings>=2.0",
    "cloudscraper>=1.2",
    "tenacity>=9.0",
    "beautifulsoup4>=4.12",
    "lxml",
    "lunardate>=0.3.0",
    "numpy",
    "pandas>=3.0",
    "pyarrow>=15",
    "matplotlib>=3.9",
    "seaborn>=0.13",
    "jinja2>=3.1",
]

[dependency-groups]
tools = [
]
testing = [
    "pytest",
    "pytest-asyncio",
]
linting = [
    "isort",
    "ruff",
]

[tool.isort]
line_length = 120

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
